# This workflow runs first, before the Java build workflow.

name: Pre-build Workflow

on:
  push:
    branches: [ "main" ]
    paths: [ "SampleDemo.java" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "SampleDemo.java" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
